// example/ew-color-picker-vite-demo/src/components/ColorPicker.vue
<template>
    <component :is="componentName" ref="colorPickerRef"></component>
</template>
<script setup>
    import "ew-color-picker/dist/ew-color-picker.min.css";
    import ewColorPicker from "ew-color-picker";
    import { defineProps, onMounted,ref } from "@vue/runtime-core";
    const props = defineProps({
        config:{
            type:Object,
            default:() => ({})
        },
        componentName:{
            type:String,
            default:"div"
        }
    });
    const colorPickerRef = ref(null);
    onMounted(() => {
        if(colorPickerRef.value){
            new ewColorPicker({ el:colorPickerRef.value,...props.config });
        }
    })
</script>

// example/ew-color-picker-react-demo/src/components/colorPicker.js
import { createRef,useEffect } from "react";
import ewColorPicker from "ew-color-picker";
import "ew-color-picker/dist/ew-color-picker.min.css";
const ColorPicker = (props) => {
    const { name,colorConfig,...restProps } = props;
    const ComponentName = name || "div";
    const colorPickerRef = createRef();
    useEffect(() => {
        if(colorPickerRef.current){
            new ewColorPicker({...colorConfig,el:colorPickerRef.current });
        }
    },[
        colorConfig,
        colorPickerRef
    ]);
    return (
        <ComponentName {...restProps} ref={colorPickerRef}></ComponentName>
    )
}
export default ColorPicker;
