// example/ew-color-picker-vue-demo/src/App.vue
<template>
    <div id="app" class="app">
        <ColorPicker :config="colorConfig"></ColorPicker>
    </div>
</template>
<script>
    import ColorPicker from "./components/ColorPicker.vue";
    export default {
        name: "App",
        components:{
            ColorPicker
        },
        data() {
            return {
                colorConfig:{
                    alpha:true,
                    changeColor(color){
                        console.log(color);
                    }
                }
            }
        }
    }
</script>
<style lang="less">
    .app {
        padding: 20px;
    }
</style>

// example/ew-color-picker-react-demo/src/App.js
import { useState } from "react";
import "./App.css";
import ColorPicker from "./components/colorPicker";
const App = () => {
    const [config] = useState({
        alpha:true,
        changeColor(color){
            console.log(color);
        }
    });
    return (
        <div className="app">
            <ColorPicker colorConfig={config}></ColorPicker>
        </div>
    )
}
export default App;
