// example/ew-color-picker-react-demo/src/components/colorPicker.js
import { createRef,useEffect } from "react";
import ewColorPicker from "ew-color-picker";
import "ew-color-picker/dist/ew-color-picker.min.css";
const ColorPicker = (props) => {
    const { name,colorConfig,...restProps } = props;
    const ComponentName = name || "div";
    const colorPickerRef = createRef();
    useEffect(() => {
        if(colorPickerRef.current){
            new ewColorPicker({...colorConfig,el:colorPickerRef.current });
        }
    },[
        colorConfig,
        colorPickerRef
    ]);
    return (
        <ComponentName {...restProps} ref={colorPickerRef}></ComponentName>
    )
}
export default ColorPicker;

// example/ew-color-picker-vue-demo/src/components/ColorPicker.vue
<template>
    <component :is="componentName" ref="colorPicker"></component>
</template>
<script>
import "ew-color-picker/dist/ew-color-picker.min.css";
import ewColorPicker from "ew-color-picker";
export default {
    name:"ColorPicker",
    props:{
        componentName:{
            type:String,
            default:"div"
        },
        config:{
            type:Object,
            default:() => ({})
        }
    },
    data(){
        return {
            instance:null
        }
    },
    mounted(){
        const instance = this.$refs.colorPicker;
        this.instance = new ewColorPicker({
            ...this.config,
            el:instance
        })
    }
}
</script>
